# Generated by Django 3.1 on 2020-09-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_auto_20200830_1157'),
        ('order', '0012_auto_20200824_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopping.product'),
        ),
    ]
