# Generated by Django 3.1.1 on 2020-09-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phone_field.models
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(default='img/profile/avatar/default.jpg', upload_to=profiles.utils.build_avatar_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('phone', phone_field.models.PhoneField(max_length=31, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
