# Generated by Django 3.0.8 on 2020-07-24 21:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200724_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='', max_length=31),
            preserve_default=False,
        ),
    ]
