# Generated by Django 3.0.9 on 2020-08-03 18:07

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200724_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(upload_to=profiles.utils.build_avatar_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Avatar'),
            preserve_default=False,
        ),
    ]
