# Generated by Django 3.1 on 2020-09-04 10:32

from django.db import migrations
import imagekit.models.fields
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200803_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='original',
            field=imagekit.models.fields.ProcessedImageField(default='img/profile/avatar/default.jpg', upload_to=profiles.utils.build_avatar_path),
        ),
    ]
