# Generated by Django 3.0.8 on 2020-07-26 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='workers',
            field=models.ManyToManyField(null=True, related_name='working_at_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
