# Generated by Django 3.0.9 on 2020-08-04 11:53

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import shopping.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200730_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(upload_to=shopping.utils.build_product_picture_path)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(upload_to=shopping.utils.build_store_logo_path)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(upload_to=shopping.utils.build_store_logo_path)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.ProductPicture'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.StoreCover'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.StoreLogo'),
        ),
    ]
