# Generated by Django 3.0.9 on 2020-08-11 14:26

from django.db import migrations
import imagekit.models.fields
import shopping.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20200804_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecover',
            name='original',
            field=imagekit.models.fields.ProcessedImageField(upload_to=shopping.utils.build_store_cover_path),
        ),
    ]
