# Generated by Django 3.1 on 2020-08-29 14:09

from django.db import migrations
import imagekit.models.fields
import shopping.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20200824_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecover',
            name='original',
            field=imagekit.models.fields.ProcessedImageField(default='img/store/cover/default.jpg', upload_to=shopping.utils.build_store_cover_path),
        ),
        migrations.AlterField(
            model_name='storelogo',
            name='original',
            field=imagekit.models.fields.ProcessedImageField(default='img/store/logo/default.jpg', upload_to=shopping.utils.build_store_logo_path),
        ),
    ]
