# Generated by Django 3.1.1 on 2020-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0030_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=2.5, max_length=5),
        ),
    ]
