# Generated by Django 3.1.1 on 2020-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0033_auto_20200914_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
