# Generated by Django 3.0.9 on 2020-08-11 20:50

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20200811_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='value_currency',
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.FloatField(),
        ),
    ]
