# Generated by Django 3.0.9 on 2020-08-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20200814_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Price'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ManyToManyField(related_name='pictures', to='shopping.ProductPicture'),
        ),
    ]
