# Generated by Django 3.0.9 on 2020-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20200814_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(to='shopping.ProductPicture'),
        ),
    ]
