# Generated by Django 3.0.9 on 2020-08-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_auto_20200817_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='store',
        ),
    ]
