# Generated by Django 3.1.1 on 2020-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_auto_20200915_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
