# Generated by Django 3.1 on 2020-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='channel_name',
            field=models.CharField(max_length=128),
        ),
    ]
