# Generated by Django 3.1.1 on 2020-09-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20200910_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
    ]
