# Generated by Django 3.0.8 on 2020-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.IntegerField(),
        ),
    ]
