# Generated by Django 3.0.8 on 2020-07-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200727_1824'),
        ('order', '0002_auto_20200728_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='shopping.Store'),
            preserve_default=False,
        ),
    ]
