# Generated by Django 3.0.9 on 2020-08-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200813_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='store',
        ),
    ]
