# Generated by Django 3.0.9 on 2020-08-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_auto_20200817_1115'),
        ('order', '0005_remove_discountcode_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='shopping.Store'),
            preserve_default=False,
        ),
    ]
