# Generated by Django 3.0.9 on 2020-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_discountcode_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_codes',
            field=models.ManyToManyField(related_name='orders', to='order.DiscountCode'),
        ),
    ]
