# Generated by Django 3.1 on 2020-08-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_auto_20200822_1307'),
        ('order', '0008_order_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopping.store'),
            preserve_default=False,
        ),
    ]
